DOT-1649 Make Geocoder more robust
TheRestartProject/restarters.net pull request #329
Opened 2021-06-16 14:01 UTC by edwh

We don't quite understand what input causes this problem, but we can tell what the fix is.

2021-06-17 14:40 UTC, ngm requested changes
After trying for a while to try and get the geocoder fail and return false during group creation - it appears that group creation is not using it. :sweat_smile: 

Group creation seems to be using an old method - /home/restart/Code/restarters/app/Http/Controllers/GroupController.php:146 

The old method also sets a country based on the country returned from Google's geocoding.

I think we could probably update Geocoder.php to return the country, and then use it for the group create?

2021-06-24 12:03 UTC, ngm reviewed
Looks good and nice to have deprecated the old Fixometer method.

Is it possible to add tests around the create method in GroupController and the postProfileInEdit and postRegister methods in UserController, for both happy and failing geocoding paths?

2021-06-24 15:03 UTC, edwh commented
Yes, it is.  Added those now.

2021-06-28 10:16 UTC, ngm approved these changes

2021-07-28 16:11 UTC, merged